spring:
  datasource:
    url: jdbc:mysql://mysql.middleware:3306/todolist?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: todouser
    password: todolist
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

cors:
  origins: "http://front.todo-list.svc.cluster.local"
  maxAge: 3600